name: restoup_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  country_code_picker: ^3.3.0
  water_drop_nav_bar: ^2.2.2
  carousel_slider: ^5.0.0
  http: ^1.2.2
  flutter_file_dialog: ^3.0.2
  flutter_dotenv: ^5.1.0
  minio: ^3.5.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  crypto: ^3.0.5
  flutter_stripe: '>=11.5.0 <12.0.0'  # Intervalle pour flutter_stripe

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  
    - .env