name: restoup_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1 # Ajouté ici avec une version (ajuste selon besoin)
  flutter_svg: ^2.0.17
  country_code_picker: ^3.3.0
  water_drop_nav_bar: ^2.2.2
  carousel_slider: ^5.0.0
  # google_fonts: ^6.2.1
  # ionicons: ^0.2.2
  # file_picker: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro # Corrigé : placé au bon niveau d'indentation
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700